### ISSUE TITLE
No spotify devices found

### ISSUE THREAD

**Issue by v0d0r** [forslund/spotify-skill#102]
Disclaimer: Not sure if this is a skill bug per say or raspotify or the way spotify connect works.

Initially when I installed the skill and I also noticed it now when I do not use it for a day or two.
When I try and play something from spotify or ask "what spotify devices are available". I always get response "No spotify devices are available".
I initially though maybe its raspotify that died so restarted the daemon regardless but still nothing.
Once I use the android Spotify app and search for devices I see raspotify and are able to stream music to it.
Once its started playing and I stop again.  I try the "what spotify devices are available" and now finds my mobile phone and raspotify as available devices.

**Comment by forslund** [comment]
Are you running on picroft? If so have you enter username / password in the raspotify config? If you haven't the raspotify instance is in "discovery mode" which means it can be detected by the spotify phone app and when connected to will get credentials to be associated with your account.

After this it would be detectable by the mycroft skill

**Comment by v0d0r** [comment]
I am running on RPI yes however I did not install the picroft image. I have a iqaudio DAC and could not get audio working so I used iqaudio's image and then manually installed MyCroft.   That said I never entered the username and pasword into the raspotify config. I did that now I will give it a try and see how it goes. Thanks

**Comment by v0d0r** [comment]
That seemed to have done the trick. Sorry that was my bad.
