### ISSUE TITLE
Remove name field from settingsmeta

### ISSUE THREAD

**Issue by forslund** [forslund/spotify-skill#111]
The settingsmeta no longer require the "name" field in the outermost region. This should be removed.

**Comment by ragrag** [comment]
by outermost region you mean inside skillMetadata?

**Comment by forslund** [comment]
I mean the one outside of skillsMetadata, [L2](https://github.com/forslund/spotify-skill/blob/19.08/settingsmeta.json#L2)

**Comment by forslund** [comment]
Resolved by #112
