### ISSUE TITLE
Restriction to my playlists

### ISSUE THREAD

**Issue by jshep321** [forslund/spotify-skill#120]
Hi,
I'm having trouble getting my playlists to play.  What is the recommended terminology to play only my playlists?  Or perhaps there is a way to restrict playlist searching?  

I have a "Christmas 2019" playlist.  mycroft gets the "play christmas 2019 playlist" utterance correct and then plays something truly unexpected:
 _play christmas 2019 playlist                                                                      
 >> Just one moment while I look for that
 >> Listening to 2019 Electronica Playlist For Christmas Lounge by Various Artists._        

Advice?

**Comment by forslund** [comment]
Hi,

Try "play the playlist Christmas 2019"

**Comment by jshep321** [comment]
Aha thanks!  Any documentation on the expected verbiage or do I need to go through the skill code?  I plan to write my own skill in the near future but not yet familiar with it.

**Comment by forslund** [comment]
We should probably expand the list example phrases in the readme to include more of the specifiers

play something by X
play the artist X

play the album X (by Y)
play the record X (by Y)

play the song X (by Y)
play the track X (by Y)
play the playlist X

**Comment by jshep321** [comment]
Yep, would be good!  

Also, it looks like searching your own playlists is only supported in the app, not desktop.  Probably not supported in my raspotify/librespot.

https://community.spotify.com/t5/Desktop-Windows/Search-in-OWN-playlists/td-p/1555294

**Comment by forslund** [comment]
The skill has sort of a workaround for it. It periodically fetches the user's playlists and does an internal search through this list before doing the search through the public playlists.

My intention is to make it possible to specify "play my playlist X" to only search the users playlists.
