### ISSUE TITLE
skill settings not appearing

### ISSUE THREAD

**Issue by JopStro** [forslund/spotify-skill#130]
have installed the skill but the preferences do not show up on home.mycroft.ai.
The skill does also not register as installed on the marketplace (green tick if thats what it means, first time using mycroft). I am using picroft pn the pi3 model B, I have not yet tested the issue with other skills but will update when I have.

**Comment by forslund** [comment]
Hi, thanks for reporting, first of all the Marketplace is not working at the moment so the skill will not show up there correctly.

A couple of questions:

- What method did you use to install the skill? voice or msm from the command line?
- Does the voice command "what spotify devices are available" return an answer like
"Unable to authorize with the Spotify service. Please go to Skill settings at home dot mycroft dot ai to verify your username and password and to Connect to Spotify."
- Are other skill settings listed on home.mycroft.ai under the skills tab? For example the weather skill should have settings. And is the Spotify skill listed but without settings?

**Comment by JopStro** [comment]
Oh, that makes sense.

I installed via voice

It replies saying "an error has occurred while processing spotify skill"

No other skill settings are listed

**Comment by JopStro** [comment]
![2020-01-05-165101_1280x720_scrot](https://user-images.githubusercontent.com/33031853/71783228-a4f3b600-2fdb-11ea-8f15-39d72f26b264.png)
the page looks like this

**Comment by forslund** [comment]
That looks sort of bad :/ somehow no skills manifest has been uploaded or anything of the kind.

I'm going to try to reproduce with a fresh user tomorrow but it looks more like a mycroft-core issue...If you can it would be good to see your `/var/log/mycroft/skills.log` if you could upload it to pastebin.com or similar site.

**Comment by JopStro** [comment]
Heres the skills.log file

https://pastebin.com/3GtRVBRN

**Comment by JopStro** [comment]
Also it may be important to note that during the setup process I took exceptionally long to input the activation code, such that a new code was generated. That may have made a difference, just to keep in mind I guess.

**Comment by JopStro** [comment]
Fixed it, just reset the device, must have been the issue I mentioned above as that is all I did differently

**Comment by forslund** [comment]
Thanks for reporting back with that info I'll do some tests anyway trying to reproduce.

**Comment by forslund** [comment]
Thanks for flagging this we found an issue in the picroft script causing the mycroft dependencies not install as intended, this would block the settings from updating.
