### ISSUE TITLE
Can't connect to authorize with Spotify

### ISSUE THREAD

**Issue by bresslem** [forslund/spotify-skill#150]
Hi! 
I just tried to install the skill for the first time but anytime I click on the "Connect" Button after I log into Spotify I just get a blank page that reads "INVALID_CLIENT: Failed to get client". 
Thanks for the great work! Hope this can be fixed :)

**Comment by forslund** [comment]
Hi, sadly Spotify disabled the Api Key for the skill last week. They don't allow the use of the API for voice applications, I missed this clause when I created the skill 3 years ago. There's a [post about it in the forums](https://community.mycroft.ai/t/attention-are-you-a-spotify-user-spotify-disabled-on-mycroft/9320)

I'm trying to get in touch with Spotify to get an API key but they've so far not been willing to reply. In the meantime I'll be working on allowing users to supply their own key (and take responsibility for violating the terms of usage of the development platform) but it's a couple of days away before I have the basics set up and then some time before I can create a smooth user experience for that. (I'm really hoping to get in touch with Spotify and get official sanction for using their api for voice)

**Comment by bresslem** [comment]
Thanks for the quick answer! I just opened a support ticket with Spotify. Hope this can be resolved :)

**Comment by Y0ngg4n** [comment]
@bresslem any updates here?
