### ISSUE TITLE
Missing lower() at regex functions

### ISSUE THREAD

**Issue by Y0ngg4n** [forslund/spotify-skill#153]
I am currently writing a Deezer skill, and i try to reuse the code here, but it attracted my attention, that there is no .lower() of the phrase, so it only matches the Regex with right case.

**Comment by forslund** [comment]
Good catch, should add ` re.IGNORECASE` to those to be extra safe.

Looking forward to trying the Deezer skill!

**Comment by Y0ngg4n** [comment]
@forslund Yes i will try to get it finished but currently you can just play tracks and playlists but it is still full of bugs XD. You can watch the repo if you want: https://github.com/Y0ngg4n/deezer-skill
