### ISSUE TITLE
Play a random album from an artist

### ISSUE THREAD

**Issue by pfefferle** [forslund/spotify-skill#171]
Especially for audiobooks and radioplays, it would be nice to have something like "`play an (random) album from {artist}`".

**Comment by forslund** [comment]
Should also "play a (random) track from {artist}" be added you think?

**Comment by pfefferle** [comment]
I thought this is the default behavior when I play an artist?!?

**Comment by forslund** [comment]
It's not a single track if I recall correctly, it's the artists top tracks. So there's no way to play a single random track.

**Comment by pfefferle** [comment]
I see! then it definitive makes sense!
