### ISSUE TITLE
auth.py file missing

### ISSUE THREAD

**Issue by oskar18j** [forslund/spotify-skill#172]
I have a problem i tried to run the auth.py file but it does not work   then i looked into the folder directory and there is no auth.py file 

/opt/mycroft/skills/mycroft-spotify.forslund $ ls /opt/mycroft/skills/mycroft-spotify.forslund 
CONTRIBUTORS  LICENSE  __pycache__  requirements.sh   settingsmeta.json  spotify.py
__init__.py   locale   README.md    requirements.txt  Spotify_Icon.png   test

**Comment by forslund** [comment]
Hi sounds like it's not up to date (the one installed by mycroft is the old version.) Can you try to ask mycroft to "install the beta version of the spotify skill"

or

run
```
cd /opt/mycroft/skills/mycroft-spotify.forslund
git checkout 21.02
git pull
```

Generally in the mycroft-core folder you can run

```
./bin/mycroft-pip install -r /opt/mycroft/skills/mycroft-spotify.forslund/requirements.txt
```

Then you should be able to find and use the auth.py file

**Comment by oskar18j** [comment]
that worked fine thank you very much.
But now I have a different problem because every time I try a comment Mycroft answers with i don't know what that means

                                                                                                                                       
 play discover weekly                                                                                                                                                   
     Just one moment while I look for that                                                                                                                    
 Sorry, I don't know how to play discover weekly 

Utterance: ['what spotify devices are available']
QuestionsAnswersSkill | Searching for what spotify devices are available
QuestionsAnswersSkill | Timeout occured check responses

it seems like mycroft is not recognizing the spotify skill

**Comment by forslund** [comment]
Which method did you use?
If you haven't try to restart Mycroft, do that. If there still is an issue, check the `skills.log` in `/var/logs/mycroft`

And see if it says anything of why the skill didn't load.

**Comment by oskar18j** [comment]
I am so stupid for not trying the most obvious solution if something is not working hahahaha.
thank you very much. that was great support and fast too
really appreciate it

**Comment by archonic** [comment]
I was also confused by the old instructions on the Mycroft skills page. I was right about to say I had done the steps here and it wasn't working saying something like "I'm not connected to your Spotify account" but when I retried, it worked 🎉. Think we could get the Mycroft skills page updated?

Small follow up question: I can list a few spotify devices, but not all of them, and I can't seem to switch output to other devices. Is that not yet a feature of the skill?

**Comment by forslund** [comment]
Hi @archonic, glad it worked for you in the end. There is an pending PR to mycroft-skills with the updated readme. but I can refresh that PR, there has been some changes.

Regarding the listing devices / transfering:
- Listing can only find logged in devices. Things that are in "discover mode" can be technically be found but needs some magic to perform the login so they aren't listed. Things like sonos devices has encrypted endpoints which I'm not sure how to tackle.
- Transferring should work (TM), as long as the device is found when listing devices it should be possible to say "transfer spotify to [device]"

If the transferring doesn't work like above please file a new issue for that.

**Comment by forslund** [comment]
I'm closing this issue since the original issue was resolved.
