### ISSUE TITLE
Unable to authorize with the spotify service

### ISSUE THREAD

**Issue by whitewallsaregreay** [forslund/spotify-skill#176]
Just checking if this skill still works with updated instructions?

I'm running on Ubuntu 22.04 LTS

Spotify is installed and logged in with a premium account.  I've gotten through the auth.py issues and now when I ask to play spotify, mycroft tells me to verify my username and password.

When I try to click connect on the settings page, it fails, but I'm certain I'm using the correct credentials.

**Comment by forslund** [comment]
Hi,

You shouldn't have a "Connect" button on the skill page so that is suspicious. Could you have 2 different versions of the skill on the mycroft skill page? they show up in tabs.

As far as I know this is still working but I'll re-verify the setup when I get back from work tonight.

**Comment by whitewallsaregreay** [comment]
I only have one tab on the skill page.

I installed via voice command, if that matters.

Should I try re-installing?  If so, what are the proper steps?  I got it working so far by scouring this issue board.

**Comment by whitewallsaregreay** [comment]
I followed your instructions here: https://github.com/forslund/spotify-skill/issues/163#issuecomment-860009675

This solved the problem.  Thank you for writing this skill!

**Comment by forslund** [comment]
Glad you got it working!
