### ISSUE TITLE
Music stops when wake word is triggered

### ISSUE THREAD

**Issue by XxCRSxX** [forslund/spotify-skill#18]
Loving the skill so far! But on annoying thing I've noticed is that the music stops when you say the wake work 'Hey Mycroft'.

Appreciate your work man 👍

**Comment by forslund** [comment]
Glad you like it!

The idea is that the music pauses for 5 seconds and then resumes when the wake word is heard so Mycroft can hear the request properly.

Does the music stop and then not resume?

What platform are you on?

**Comment by XxCRSxX** [comment]
It does continue the music again after 5 seconds but my problem is MyCroft often thinks I’m saying the wake up word when I’m not so it interrupts Spotify :/

I’m currently running it on a Raspberry Pi 3 but just about to try MyCroft + Plasmoid

**Comment by forslund** [comment]
I understand. In that case an option in the settings might be the way to go. Making it possible to disable the auto-pause

**Comment by spagy** [comment]
Looks like the audio ducking feature has been made optional. Can this issue be closed now?

**Comment by forslund** [comment]
Indeed. Closing.

**Comment by kmccurley** [comment]
I've gotten two skills working with the CommonPlaySkill and I face the same need for ducking. It leads me to think that the functionality for ducking really belongs in CommonPlaySkill rather than the things that inherit from it.
