### ISSUE TITLE
Any plan to port this skill to OVOS

### ISSUE THREAD

**Issue by goldyfruit** [forslund/spotify-skill#185]
Hi @forslund 

Do you plan any port to Open Voice OS skill's API?

IMHO, this skill is one the most important within the Mycroft AI ecosystem, having it working into the Open Voice OS ecosystem would be a really nice to have.

Thanks :+1:

**Comment by forslund** [comment]
Yes there is a plan. I've had some issues getting the ovos dev environment up and running (mainly due to a lack of time), but recently got something ok-ish going so I'll be giving it a shot in the coming week

**Comment by forslund** [comment]
Hi again, there's been some work done on this and there is an [OVOS skill repo](https://github.com/forslund/ovos-spotify-skill). The skill is still in early days and isn't quite functional yet and requires some patches to OVOS.

Just wanted to let you know the work has begun and is moving forward.
