### ISSUE TITLE
Just plays were it stoped last time

### ISSUE THREAD

**Issue by andlo** [forslund/spotify-skill#43]
If I ask #hey Mycroft Play the album Hello Nasty on Spotify" he just starts laying Spotify - where it were last time it were stoped. What are I missing in getting him to find and play some music ?

**Comment by forslund** [comment]
Hi, thanks for reporting. This is likely a too general intent triggering on "play + spotify". I shall remove that one.

In the meantime you can try with just: *hey Mycroft Play the album Hello Nasty*
