### ISSUE TITLE
"Hey Mycroft Play Spotify" doesn't work

### ISSUE THREAD

**Issue by dschweppe** [forslund/spotify-skill#5]
Is it possible to start playing the last song, album, station or playlist that the user listened to on Spotify? Mycroft's response could be:
"Playing the last song you listened to on Spotify" or "playing where you left off on Spotify"

**Comment by forslund** [comment]
It is definitely possible.

**Comment by forslund** [comment]
This should be working as of 1 minute ago.

play spotify, continue current spotify playlist

**Comment by forslund** [comment]
Closing, reopen if there are problems with this.
