### ISSUE TITLE
command words works half way

### ISSUE THREAD

**Issue by Renswind** [forslund/spotify-skill#51]
Hello
I have stumbled uppon the problem that the command "play *artist*" dosent work. Mycroft only say "i dont under stand" and so on.
If i tell it to play something with *artist*, i get all wierd random result and not what i was asking for, or no result at all.
I have installed raspotify.
Mycroft acknowledged that it have it in the list of devices.
When telling play *artist* or *song* mycroft dont understand.

Is the play function broken?

**Comment by Renswind** [comment]
@forslund 
Hi!
I have localized the problem, and that was when you set location on your picroft, the site is checking the ip of your extrernal ip, in other words the exit point of your ISP. Mycroft location is checked throu this and then add the city instead of the country. Its in mycroft local settings that is the problem i found out. Now i can play with the  spotify-skill by saying "play <artist>/play something with <artist>"

I will comeback with more info about the local settings that makes almost every skill work half half with what its supposed to.

**Comment by forslund** [comment]
Humm, that sounds strange. The skill doesn't use the mycroft location at all. Is it librespot/raspotify that does this?

**Comment by forslund** [comment]
I'm going to close this issue since a large refactoring has been performed removing basically all of the code that this issue referred to. Feel free to reopen if you think this is incorrect.
