### ISSUE TITLE
Repeatedly pausing/resuming after vocal request

### ISSUE THREAD

**Issue by ghost** [forslund/spotify-skill#60]
Very often, after a song is asked, it starts playing it, and then pauses/unpauses it repeatedly for a while.
I can't understand why.

**Comment by forslund** [comment]
I've gotten reports of this previously but I've not been able to reproduce it :(

The current workaround is to disable the audio ducking in the skill. Go to home.mycroft.ai -> skills, find the spotify skill and uncheck **Use audio ducking**

**Comment by forslund** [comment]
If you can find the reason for this or if you find more information I'd be happy to work on this.

**Comment by ghost** [comment]
Okay, thank you.

**Comment by forslund** [comment]
This behavior has been updated and I think this can no longer occur. Feel free to reopen if this still happens do you.
