### ISSUE TITLE
Skill fails without feedback

### ISSUE THREAD

**Issue by g3rb3n** [forslund/spotify-skill#61]
Often when a command fails there is no feedback why it fails, mycroft does not respond and just stays silent, also the logs do not provide any reason why the skill command has failed.

**Comment by g3rb3n** [comment]
After investigating the code I figured out why this happens.
The code often follows the pattern:
```
if condition:
  do_something()
```
or
```
try:
  do_something()
except:
  pass
```
While it is good to prevent errors, it is better to handle abnormal conditions in an understandable way. E.g.:
```
if not condition:
  return handle_error('condition failed')
do_something()
```
and
```
try:
  do_something()
except Exception as e:
  handle_error(e)
```
handle_error might be doing something like talk back to the user and at least always log the error. In this way it is clear for the end user why something fails without needing to dive into the logs, or after looking at the logs why something fails without needing to dive into the source code.

**Comment by forslund** [comment]
Hi, I'll try to improve the feedback.

Can you also provide which platform you're running?

**Comment by g3rb3n** [comment]
Mark I

**Comment by forslund** [comment]
On the Mark-1 the errors often occur in the librespot player and debug capture was recently turned off by default since it generates a lot of not very interesting logs. You can add a `"librespot_log": true` to the `settings.json` of the skill to enable the logs to be captured.

**Comment by g3rb3n** [comment]
I do not use the Mark I as playback device, since I have a hifi set which provides much better sound quality. I just want to use the Mark I to control Spotify. Maybe it would be a nice feature to be able to disable the LibreSpot client.

I was more referring to the cases in the SpotifySkill where there is missing feedback. For example when there is no connection to Spotify for whatever reason, I would like Mycroft to tell me that it can not play music for that reason. Currently it just ignores my command when I say 'play something'. It would be nice if Mycroft would say something like "Sorry I can not play music since I am not connected to Spotify"

**Comment by forslund** [comment]
I'm pretty sure it used to say something, it probably got lost when we overhauled everything for the common play system. I'll add it back. Thanks for letting me know.

**Comment by forslund** [comment]
Closing this since most of this has been incorporated. Thanks for your contribution on this!
