### ISSUE TITLE
"Play Music" command not working as expected

### ISSUE THREAD

**Issue by Deukhoofd** [forslund/spotify-skill#80]
Expected behaviour would be that the music continues playing from pause. Unfortunately current behaviour is that it searches for a song or album containing "Music".

**Comment by forslund** [comment]
Hi thanks for reporting.
The play/pause/next track/etc isn't handled in this skill, it's handled in [mycroft-playback-control](https://github.com/MycroftAI/skill-playback-control). Would you mind opening the issue over there?

**Comment by Deukhoofd** [comment]
Ah, good to know, thank you for the response!
