### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by BNolet** [forslund/spotify-skill#83]
Add capability of using phrases like "Start playlist XXXX on spotify" and "Play my XXXX playlist"

**Comment by forslund** [comment]
Playlists should already be working like that. Let me verify.

**Comment by forslund** [comment]
Ok, I've checked that this works...

*Play the playlist discover weekly* starts the playlist as expected.

**Comment by BNolet** [comment]
Discover Weekly is a specific dynamic playlist made by Spotify if I remember correctly. I couldn't get it going with playlists with names like "beast mode" and "background"

**Comment by forslund** [comment]
Ah then I understand. The skill only fetches playlists tied to your user. I'll look into searching for general playlists as well.

**Comment by BNolet** [comment]
Yes, these playlists are tied to my user

**Comment by forslund** [comment]
That is strange, all my playlists are working for me. Could these playlist be collaborative playlists?

**Comment by BNolet** [comment]
It's possible it's a syncing issue and that MyCroft needed a restart, I'll test this evening. 

No these are not collaborative

**Comment by BNolet** [comment]
Tried again and it's just giving me some random playlist from spotify rather than the playlist I asked for.

**Comment by forslund** [comment]
Can you verify the STT pickup of the thing you say? And give me some examples.

The procedure for playlists is:

Load the user's playlists into a list
Get the list name from STT
Do a fuzzymatch on the string based on the list of playlists and find the "closest" match
Start playback of that playlist.

**Comment by BNolet** [comment]
Sorry for my ignorance but what is STT?

**Comment by forslund** [comment]
Oh sorry, Speech To Text. Basically that the text that the skill matches an existing playlist

**Comment by BNolet** [comment]
So I think it might be grabbing the right playlist but it's not marking that it's actually my playlist that the songs are being played from

**Comment by forslund** [comment]
Can you give me an example of playlists that get played?

Also does the songs when playing discover weekly match the songs of your discover weekly list?

**Comment by BNolet** [comment]
Discover weekly gives me a Piano playlist: 
![image](https://user-images.githubusercontent.com/10198484/54079667-cba76a00-42ae-11e9-86b2-6532659d57f0.png)

**Comment by BNolet** [comment]
Beastmode playlist matches with confidence 1.0: 
![image](https://user-images.githubusercontent.com/10198484/54079693-45d7ee80-42af-11e9-8bb3-63bfdb2823f7.png)

However, in Spotify it doesn't say that it's actually playing the playlist. It just queues up the songs from the playlist.

![image](https://user-images.githubusercontent.com/10198484/54079703-761f8d00-42af-11e9-8523-4e1d0c5824fd.png)

**Comment by forslund** [comment]
Thanks for that information. Seems like it can't find your discover weekly playlist.

The way playlist playback is implemented is a bit weird, because it does exactly what you say it does: fetches all tracks from the playlist loads them and starts playback. I'll see if I can refine that to simply playing the playlists...

**Comment by BNolet** [comment]
Interesting 🤔 If the current implementation starts a new context, it might result in the playlist just "stopping" at the end of the queued list of songs.

You might want to simply PUT https://api.spotify.com/v1/me/player/play and then in the context_uri specify the playlist itself rather than providing the array of URIs of tracks in said playlist. 

Source: https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/

edit: ugh, idk how I managed to hit close on the issue

**Comment by BNolet** [comment]
test

**Comment by forslund** [comment]
Yeah that's basically what's done for albums and artists but there were (back in the day atleast) something with playlists that made it not working...As I said above I'm going to revisit this.

**Comment by forslund** [comment]
Pushed the branch [feature/playlist](https://github.com/forslund/spotify-skill/tree/feature/playlists) feel free to try it and see if it works better. It uses the playlist as a context_uri like you suggested.

**Comment by BNolet** [comment]
Worked like a charm! Thanks you @forslund!
