### ISSUE TITLE
Cannot play song with same name as playlist

### ISSUE THREAD

**Issue by BNolet** [forslund/spotify-skill#86]
Opening this one for the sake of completeness as I'm sure this will be an issue.

I suggest listening for the word "playlist" along with the search request.

For example, if I say "Play beast mode" it should play the first song in a spotify search (I think it's Beast Mode by A Boogie Wit da Hoodie). But if I say "play my beast mode playlist" it should play my playlist titled beast mode. 

I know it may sound a little pedantic, but I'm sure this case will pop up in the future with someone else.

**Comment by forslund** [comment]
Currently songs can't be played through generic play X requests. Instead a song needs to be requested, "play the song X"

**Comment by BNolet** [comment]
> Currently songs can't be played through generic play X requests. Instead a song needs to be requested, "play the song X"

Heheh, I figured that one out after I posted this, which is why I closed it. Thanks for the feedback :)
