### ISSUE TITLE
Increase the flexibility of artist regex

### ISSUE THREAD

**Issue by augray** [forslund/spotify-skill#93]
I had a hard time getting this skill to play music by a requested artist. Some things I tried:
"Play music by `<artist>` on Spotify"
"Play songs by `<artist>` on Spotify"
"Play `<artist>` on Spotify"

It would be helpful if more standard variations were supported for playing music by specific artists.

**Comment by augray** [comment]
Here's a PR if you want it: https://github.com/forslund/spotify-skill/pull/94

**Comment by augray** [comment]
The case "Play `<artist>` on Spotify" is obviously a bit more complex, and would likely need to be handled by a more sophisticated mechanism. So I left that one out.

**Comment by forslund** [comment]
#94 Merged. Closing this Issue. Thank you very much for contributing :)

**Comment by augray** [comment]
No problem :+1:
