### ISSUE TITLE
Switch to the Spotify logo in the readme

### ISSUE THREAD

**Issue by forslund** [forslund/spotify-skill#97]
The logo can be found at https://developer.spotify.com/branding-guidelines/ (Green logo on white)

**Comment by dvdvgt** [comment]
May I take this on?

**Comment by forslund** [comment]
Go for it!

**Comment by dvdvgt** [comment]
Thanks @forslund ! I'll create a PR as soon as the hacktoberfest event starts so it counts towards my contributions if you don't mind :)

**Comment by forslund** [comment]
Resolved by #110
