### ISSUE TITLE
Mycroft controls spotify on other devices, but not itself.

### ISSUE THREAD

**Issue by JaredTRand** [forslund/spotify-skill#99]
Similarly to this question: https://github.com/forslund/spotify-skill/issues/29
I could not get mycroft to play anything by itself, even with raspotify installed. It just keeps telling me there are no spotify devices available. I'm wondering if I missed a step between installing raspotify and playing it through mycroft.

Thanks for any help!

**Comment by forslund** [comment]
Hi, which platform is this on?

**Comment by arraylabs** [comment]
I'm seeing this on rpi3+ raspbian buster, mycroft git clone installation method

**Comment by AlfieJones** [comment]
I'm also experiencing this problem on the pi 4, I'll ask to play a song and it will start playing on another spotify device instead of the mycroft.

**Comment by forslund** [comment]
The skill doesn't handle playback, on the mark-1 the skill will launch a player. on Picroft this is not handled automatically.

Is raspotify installed and setup with **username**, **password** set? Is the **name** set to the same name as the mycroft device?

**Comment by AlfieJones** [comment]
Thanks for the quick response, I didn't realise playback wasn't handled by this skill. Just after posting my first comment I installed raspotify and have since got it working. Thanks again

**Comment by forslund** [comment]
Great, I'm looking at using the old libspotify to handle playback in the skill but that's it's own can of worms.

I should add a Picroft entry in the readme to make this clear. putting it on my Todo

**Comment by JaredTRand** [comment]
Oh I'm so sorry! I forgot I opened this issue, I need to pay more attention to this stuff.
But yeah, I'm running picroft on raspi 3b+. I'll try double checking the username and password stuff and see if I can work it out.

One question I had was, should the NAME be the name of the physical raspi or the name I chose on the mycroft website? I just assumed it was the latter.

**Comment by JaredTRand** [comment]
I knew I did something dumb! I forgot to uncomment the parts of the configuration file that I needed. Seems to be working fine now! Sorry for what was basically a non-issue

**Comment by forslund** [comment]
Glad you figured it out!
